//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMTDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int PID { get; set; }
        public string SKU { get; set; }
        public string PName { get; set; }
        public string PDescription { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
